name: key-value-server

dependencies:
  - base
  - bytestring
  - containers
  - servant-server
  - string-conversions
  - text
  - wai
  - warp

ghc-options:
  - -Wall
  - -Wno-name-shadowing

executables:
  key-value-server:
    main: key-value-server.hs
    source-dirs:
      - src

tests:
  specs:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec
      - http-client
      - http-types
